apiVersion: apps/v1
kind: Deployment
metadata:
  name: alice-deployment
  labels:
    app: alice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alice 
  template:
    metadata:
      labels:
        app: alice 
    spec:
      containers:
      - name: mp-python
        image: irvnet/mp-python:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: alice-config
