apiVersion: v1
kind: ConfigMap
metadata:
  name: alice-config
  namespace: mp-alice
data:
  PORT: "5000"
  SERVICE2_URL: "http://bob-service.default.svc.cluster.local:5000/polo"
  SERVICE3_URL: "http://chris-service.default.svc.cluster.local:5000/polo"