apiVersion: v1
kind: Service
metadata:
  labels:
  name: alice-service
  namespace: mp-alice
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: alice
  type: NodePort