apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob-deployment
  namespace: mp-bob
  labels:
    app: bob-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bob 
  template:
    metadata:
      labels:
        app: bob 
    spec:
      containers:
      - name: mp-python
        image: irvnet/mp-python:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: bob-config
