apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-deployment
  labels:
    app: chris-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chris 
  template:
    metadata:
      labels:
        app: chris 
    spec:
      containers:
      - name: mp-python
        image: irvnet/mp-python:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: chris-config
