apiVersion: v1
kind: ConfigMap
metadata:
  name: chris-config
  namespace: mp-chris
data:
  PORT: "5000"
  SERVICE2_URL: "http://alice-service.default.svc.cluster.local:5000/polo"
  SERVICE3_URL: "http://bob-service.default.svc.cluster.local:5000/polo"